### ISSUE TITLE
We need to track latency for calls to the outbound client URLs

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/caduceus#100]
Right now we can't track the time spent waiting on outbound client URLs to respond.  This causes the problem where network issues in between the client and caduceus are difficult to diagnose.

Ideally we will implement something like this to track the time in a useful way.

https://godoc.org/github.com/prometheus/client_golang/prometheus/promhttp#example-InstrumentRoundTripperDuration

**Comment by githubsands** [comment]
#109

**Comment by githubsands** [comment]
#129 solves this when complete

**Comment by joe94** [comment]
This is the helper utility used to perform this: https://pkg.go.dev/github.com/prometheus/client_golang@v1.6.0/prometheus/promhttp?tab=doc#RoundTripperFunc
