### ISSUE TITLE
Improper encoding of sent payload

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/caduceus#116]
Currently caduceus doesn't change any encoding based upon the `webhook.config.content_type`. Instead it uses the current encoding and sends that type as the `Content-Type` header.

Instead the sent message should be re-encoded to what ever is requested aka `webhook.config.content_type`

**Comment by kcajmagic** [comment]
This might not be an issue since the device is sending the payload, and caduceus is just forwarding along with the correct headers. Thus making the receiver read the `Content-Type` and properly decode the body.

**Comment by kristinaspring** [comment]
@kcajmagic Is this an issue? if not, can you close this issue?
