### ISSUE TITLE
Data Race in test

### ISSUE THREAD

**Issue by joe94** [xmidt-org/caduceus#150]
`TestSwSimple` under `senderWrapper_test.go` is reporting a data race 
https://travis-ci.com/xmidt-org/caduceus/jobs/216272629`

There's a comment suggesting possible solutions
https://github.com/xmidt-org/caduceus/blob/master/src/caduceus/senderWrapper_test.go#L135

**Comment by schmidtw** [comment]
The files moved earlier today, but I don't see any race conditions reported via `go test -race`.  Please reopen if you see this again/still.

**Comment by joe94** [comment]
No longer see the failures either - Thanks for checking!
