### ISSUE TITLE
Caduceus panics with non-utf string for event name

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/caduceus#151]
If you attempt to pass in a string that cannot be parsed correctly by the underlying metrics, caduceus panics.  

panic: label event: value "raw.kestrel.reports\xedNetworkDevicesStatus" is not valid UTF-8

vendor/github.com/prometheus/client_golang/prometheus.(*CounterVec).With(0xc00000ea08, 0xc05d2c21b0, 0x6, 0xc05d2c21b0)
    /root/rpmbuild/BUILD/caduceus-0.1.3/src/vendor/github.com/prometheus/client_golang/prometheus/counter.go:217 +0x79
vendor/github.com/go-kit/kit/metrics/prometheus.(*Counter).Add(0xc010491dc0, 0x3ff0000000000000)
    /root/rpmbuild/BUILD/caduceus-0.1.3/src/vendor/github.com/go-kit/kit/metrics/prometheus/prometheus.go:45 +0x5c
main.(*CaduceusOutboundSender).send(0xc001826900, 0xc01628c590, 0xe, 0xc01628c578, 0x4, 0xc0a0141b00)
    /root/rpmbuild/BUILD/caduceus-0.1.3/src/caduceus/outboundSender.go:537 +0xa44
created by main.(*CaduceusOutboundSender).dispatcher
    /root/rpmbuild/BUILD/caduceus-0.1.3/src/caduceus/outboundSender.go:444 +0x342

**Comment by schmidtw** [comment]
This seems to be something that should be done in wrp-go based on some local feedback I got.

https://github.com/xmidt-org/wrp-go/issues/25

We also should make the outgoing goroutine panic tolerant as well.

**Comment by kristinaspring** [comment]
This is fixed.
