### ISSUE TITLE
Caduceus panics due to metric cardinality issue

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/caduceus#164]
It looks like the metric cardinality is wrong for this metric:
https://github.com/xmidt-org/caduceus/blob/master/outboundSender.go#L301

**Comment by schmidtw** [comment]
https://github.com/xmidt-org/caduceus/blob/94286dd77ba28343644de15c5837fcab81255216/outboundSender.go#L292

Fixing the line number based on today.

**Comment by joe94** [comment]
Looks like the labels are added here already: https://github.com/xmidt-org/caduceus/blob/453f1410b1f109beeac7d9141eb20df4c86292d6/metrics.go#L166

Feel free to reopen if the error continues.
