### ISSUE TITLE
Check Encode Error

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/caduceus#169]
https://github.com/xmidt-org/caduceus/blob/a46649b9ae03fc771dc0070e410c6c1d5cf2b6c1/outboundSender.go#L519

@kcajmagic, is there a reason we're not checking this error? Otherwise, I think we should add a check for it.

**Comment by kcajmagic** [comment]
@kristinaspring since the message is coming from talaria as msgpack encoding, the encoding should already just work.

I’m not attached to either way. Maybe it it easier to read without checking for an error?

**Comment by kristinaspring** [comment]
I don't think we should trust our current setup to ensure that we will
never have an error here. If something changes in the future and this
causes a problem, no error checking may make this issue difficult to find.
Also I don't think checking an error hinders readability that much (and if
it does here I think we should refractor so it doesn't).

I do agree the likelihood of an error when re encoding something we have
already decoded is extremely low.

I didn't read around for full context, so if it's difficult to catch an
error there at this time I'm good with just leaving the issue open for now.

**Comment by kristinaspring** [comment]
Since we have made a design decision to not re-encode in caduceus, this is no longer relevant.
