### ISSUE TITLE
Configurable non-200 codes to retry on

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/caduceus#175]
https://github.com/xmidt-org/caduceus/blob/94286dd77ba28343644de15c5837fcab81255216/outboundSender.go#L567

if we get a 404, retrying won't help anyone.  Are there any other response codes we shouldn't retry on?

Edit: Error code handling should be configurable in Caduceus.  We need further discussion to determine the abilities we want in this handling and that will help inform how it is configurable.

**Comment by kcajmagic** [comment]
It should not retry on any 400, and 501

**Comment by kristinaspring** [comment]
Still waiting for input from @schmidtw.  Any other responses we shouldn't retry on?

**Comment by joe94** [comment]
Should retry on: 429

**Comment by joe94** [comment]
We should not retry on any well known status code that suggest a later retry will likely not succeed.

**Comment by joe94** [comment]
We need to revisit this issue after we've had some discussion on handling error codes.

**Comment by kristinaspring** [comment]
After further discussion, we agreed on having a whitelist of status codes to retry on.  These will be configurable.
