### ISSUE TITLE
Send preflight request to verify the webhook is good

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/caduceus#201]
https://github.com/xmidt-org/caduceus/blob/00ce0db65037d62ca9f45f31f191835e86bcb93b/outboundSender.go#L162

This should be configurable (able to be enabled/disabled).  When we are creating a new webhook, we should send a preflight check to the webhook's url to ensure that:
- Caduceus can reach it and receive a successful response
- the certs on that server are good

This could be done in two ways:
1. send an OPTIONS verb with Content-Length: 0, and the other side is required to respond with the valid HTTP verbs
2. send a dummy event with a clearly fake mac address (`MAC:000000000000`)

I'm not sure that this needs to be done in Caduceus.  If it's okay for the receiver of the webhook to do it, I think it should be a part of this issue:
https://github.com/xmidt-org/webpa-common/issues/475
Then if this preflight check failed, we could indicate that the webhook is bad in our response to the webhook registration request.

**Comment by joe94** [comment]
After some consideration, we decided it's not worth the big effort at the moment.
