### ISSUE TITLE
Empty queue when a webhook expires

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/caduceus#231]
https://github.com/xmidt-org/caduceus/blob/aa1419260f195f95b14c6534f40534c453c684ab/outboundSender.go#L517

Instead of allowing the dispatcher to clear the queue one event at a time when a webhook expires, call Empty() function to clear it.

**Comment by joe94** [comment]
As an event consumer, as long as I renew my registration in a timely fashion, my events will be kept right?

**Comment by kristinaspring** [comment]
As long as the webhook stays registered, no events are dropped.  When the registration expires, if it isn't renewed, we immediately begin dropping events.
