### ISSUE TITLE
Be more judicial about retrying on http error

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/caduceus#232]
https://github.com/xmidt-org/caduceus/blob/aa1419260f195f95b14c6534f40534c453c684ab/outboundSender.go#L604

@johnabass may know more about this.

**Comment by mtrinh11** [comment]
Propose to remove `retryCodes` in the caduceus config. Although configurable, caduceus config defaults to only retry on 429s. One would have to edit the yaml file to include more error codes to retry on.
Instead we propose to have the logic of which codes to retry in the `RetryCodes` function in the xhttp package. This function will retry on 408, 429, and 504 error codes. This convention will be consistent with our code in our newer services.

**Comment by kristinapathak** [comment]
Given that we haven't gotten any pushback from the community, we are moving forward with this breaking change.

**Comment by kristinapathak** [comment]
I think some further cleanup is still needed for this.
